export const productsData = [
  {
    id: 1,
    name: "Holanda Chocolate Creame",
    price: 3000,
    grams: "542 g",
    image: require("../images/Holand.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 2,
    name: "Dasam Chocolate Creame",
    price: 2500,
    grams: "1 L",
    image: require("../images/Dasam.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 3,
    name: "Dasam Chocolate Creame",
    price: 4500,
    grams: "1 Kg",
    image: require("../images/Dasam2.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 4,
    name: "Snickers Creame",
    price: 5000,
    grams: "612 g",
    image: require("../images/Snickers.png"),
    quantity: 1,
    favorite: true,
  },

  {
    id: 5,
    name: "Duetto Chocolate",
    price: 2000,
    grams: "700 g",
    image: require("../images/Duetto.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 6,
    name: "Nutella Chocolate Creame",
    price: 1000,
    grams: "1 L",
    image: require("../images/Nutella.png"),
    quantity: 1,
    favorite: true,
  },
  {
    id: 7,
    name: "Otanic Cream Chocolate",
    price: 3000,
    grams: "542 g",
    image: require("../images/Otanic.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 8,
    name: "Adorei Chocolate",
    price: 3000,
    grams: "542 g",
    image: require("../images/Adorei.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 9,
    name: "Laive Yopi Mix",
    price: 500,
    grams: "200 g",
    image: require("../images/Laive.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 10,
    name: "Pingo de leite Chocolate",
    price: 600,
    grams: "250 g",
    image: require("../images/Pingo.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 11,
    name: "Nestle Nutren",
    price: 200,
    grams: "200 ml",
    image: require("../images/Nestle.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 12,
    name: "Moni Chocolate Creame",
    price: 400,
    grams: "500 g",
    image: require("../images/Moni.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 13,
    name: "Nestle Classic",
    price: 100,
    grams: "150 ml",
    image: require("../images/Nestle_Classic.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 14,
    name: "Neugebauer ",
    price: 150,
    grams: "300 ml",
    image: require("../images/Neugebauer.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 15,
    name: "Pop Up Chocolate",
    price: 100,
    grams: "500 g",
    image: require("../images/PopUp.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 16,
    name: "M&M’s Chocolate",
    price: 200,
    grams: "1 Kg",
    image: require("../images/M&M.png"),
    quantity: 1,
    favorite: true,
  },
  {
    id: 17,
    name: "Kopiko Coffee",
    price: 100,
    grams: "20 g",
    image: require("../images/Kopiko.png"),
    quantity: 1,
    favorite: true,
  },
  {
    id: 18,
    name: "Aymore Chocolate ",
    price: 150,
    grams: "400 g",
    image: require("../images/Aymore.png"),
    quantity: 1,
    favorite: false,
  },
  {
    id: 19,
    name: "Trento Speciale Avala",
    price: 150,
    grams: "400 g",
    image: require("../images/Trento.png"),
    quantity: 1,
    favorite: false,
  },

  {
    id: 20,
    name: "Melken Chocolate",
    price: 200,
    grams: "500 g",
    image: require("../images/Melken.png"),
    quantity: 1,
    favorite: false,
  },
];

export const formatNumber = (num: number) => {
  return new Intl.NumberFormat().format(num);
};
